name: Run pylint

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py') || pylint_exit=$?
          
          # Return error only for error + fatal
          if [ $((pylint_exit & 3)) -ne 0 ]; then
            exit $pylint_exit
          fi
